name: Terraform Meraki Apply

on:
  push:
    branches: [ main ]

jobs:
  apply:
    runs-on: ubuntu-latest

    env:
      MERAKI_API_KEY: ${{ secrets.MERAKI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_TF_STATE_KEY }}

      - run: terraform init -input=false
      - run: terraform apply -auto-approve
